highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Wai Kit Chan's Resume
name: Wai Kit Chan
email: mariocwk@gmail.com
email_full: mailto:youremail@me.com
website: https://github.com/mario-852
website_full: https://jekyller.github.io/sustain
github: trending
twitter: twitter
tel: +49 0178 815 2626
tel_full: tel:+4901788152626
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Volkartstr. 84
  postcode: 80636
  city: Munich
  country: Germany
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
