highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Wai Kit Chan's Resume
name: Wai Kit Chan
email: mariocwk@gmail.com
email_full: mailto:mariocwk@gmail.com
website: github.com/mario-852
website_full: https://github.com/mario-852
tel: +49 0178 815 2626
tel_full: tel:+4901788152626
google_maps: 'https://www.google.co.uk/maps/place/Volkartstra%C3%9Fe+84,+80636+M%C3%BCnchen/@48.1593774,11.5412617,17z/data=!3m1!4b1!4m5!3m4!1s0x479e766d69eac07f:0x9f1ba6dafba2305b!8m2!3d48.1593738!4d11.5434504'
address:
  street: Volkartstr. 84
  postcode: 80636
  city: Munich
  country: Germany
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
