highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title/

port: 4000
#safe: true
url: "https://kamranali.in/vitae"
author: Kamran Ali

# edit this section with your information

baseurl: ""
title: Kamran Ali's Resume
name: Kamran Ali
email: kamranalinitb@gmail.com
email_full: mailto:kamranalinitb@gmail.com
website: kamranali.in
website_full: https://kamranali.in
github: kamranalinitb
twitter: bornShrewd
#tel: 
#tel_full: 
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: U66-14 Top Floor
postcode: 122002
city: Gugugram
country: India

plugins: 
  - jekyll-sitemap
  
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    startings: [html, head, body]
    endings: all
    ignore:
    envs: []
    blanklines: false
    profile: false

#google_analytics: UA-69300817-1
