highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Abiy Mesfin's Resume
name: Abiy Bekele
email: abiymesfin916@gmail.com
email_full: mailto:youremail@me.com
website: https://abiyp.github.io/Abiy/
github: trending
tel: +46722845794
address:
  street: Trollvägen 17
  postcode: 17 670
  city: Stockholm
  country: Sweden
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-slate